name: Build, test and deliver container

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 11 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64

      - name: Start MongoDB for integration test
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.2
          mongodb-port: 27018

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/six-letter-words:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/six-letter-words:latest